<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>Barakhloskop</AssemblyName>
    <RootNamespace>Barakhloskop</RootNamespace>
    <Product>Барахлоскоп 3000</Product>
    <AssemblyTitle>Барахлоскоп 3000</AssemblyTitle>
    <Version>1.0.0</Version>
    <SatelliteResourceLanguages>ru</SatelliteResourceLanguages>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

</Project>
